"""add user id to event name

Revision ID: 9f97c40b2176
Revises: 4f921aaa1892
Create Date: 2025-12-17 16:48:56.384539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f97c40b2176'
down_revision: Union[str, Sequence[str], None] = '4f921aaa1892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_videos_id'), table_name='photo_videos')
    op.drop_table('photo_videos')
    op.drop_index(op.f('ix_admin_email'), table_name='admin')
    op.drop_index(op.f('ix_admin_id'), table_name='admin')
    op.drop_table('admin')
    op.drop_index(op.f('ix_event_names_event_name'), table_name='event_names')
    op.drop_index(op.f('ix_event_names_id'), table_name='event_names')
    op.drop_table('event_names')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_names',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('event_names_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('event_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gsheet_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='event_names_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_event_names_id'), 'event_names', ['id'], unique=False)
    op.create_index(op.f('ix_event_names_event_name'), 'event_names', ['event_name'], unique=False)
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_pkey'))
    )
    op.create_index(op.f('ix_admin_id'), 'admin', ['id'], unique=False)
    op.create_index(op.f('ix_admin_email'), 'admin', ['email'], unique=True)
    op.create_table('photo_videos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_processed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event_names.id'], name=op.f('photo_videos_event_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('photo_videos_pkey'))
    )
    op.create_index(op.f('ix_photo_videos_id'), 'photo_videos', ['id'], unique=False)
    # ### end Alembic commands ###
